"""Flexible-shape distributional losses (audit §6, item F5).

Each loss consumes the raw output matrix of a flexible-shape network head
(``y_pred[..., k]`` columns mapped to distribution parameters) and routes the
elementwise NLL through the unified ``BaseLoss._reduce`` pipeline
(mask = zero-fill, optional sample weights).

References:
- Azzalini (1985), "A class of distributions which includes the normal ones",
  Scand. J. Statist. 12, 171-178 (skew-normal).
- Azzalini & Capitanio (2003), "Distributions generated by perturbation of
  symmetry with emphasis on a multivariate skew t-distribution", JRSS-B 65,
  367-389 (skew-t).
- Ferrari & Cribari-Neto (2004), "Beta regression for modelling rates and
  proportions", J. Appl. Stat. 31, 799-815.
- Johnson, Kotz & Balakrishnan (1994), Continuous Univariate Distributions Vol. 1
  (Johnson SU; Shenton-Bowman moment quadrants for parameter interpretation).
- Jones & Pewsey (2009), "Sinh-arcsinh distributions", Biometrika 96, 761-780.
- Coles (2001), "An Introduction to Statistical Modeling of Extreme Values"
  (GEV parameterization).
- Koenker & Machado (1999), "Goodness of fit and related inference processes
  for quantile regression", JASA 94 (asymmetric Laplace / check-loss duality).
- Duan et al. (2020), "Adaptive Distributional Regression by Minimizing Sqr
  Loss" (SQR: sorted quantile levels trained with mean pinball loss).
"""

from __future__ import annotations

import math
from typing import Optional

import torch
import torch.nn.functional as F
from torch import Tensor

from .base import BaseLoss
from .loss_registry import register_regression_loss

_SQRT2 = math.sqrt(2.0)
_LOG_2PI = math.log(2.0 * math.pi)
_HALF_LOG_2PI = 0.5 * _LOG_2PI
_TINY_F32 = float(torch.finfo(torch.float32).tiny)


# ---------------------------------------------------------------------------
# shared numerics
# ---------------------------------------------------------------------------


def _log_normal_cdf(x: Tensor) -> Tensor:
    """Log standard-normal CDF, exact in both tails.

    Delegates to :func:`torch.special.log_ndtr`, which uses an asymptotic
    expansion in the far lower tail. The previous ``log(clamp(Phi, tiny))``
    form saturated at ``log(float32 tiny) ~ -87`` (``x < ~-13``) in every
    dtype, zeroing the gradient of the skew-normal NLL w.r.t. alpha.
    """
    return torch.special.log_ndtr(x)


def _betacf(a: Tensor, b: Tensor, x: Tensor, itmax: int = 300, eps: float = 3e-14) -> Tensor:
    """Continued-fraction evaluation of the incomplete beta function
    (modified Lentz's method), vectorized over ``x``."""
    tiny = torch.finfo(x.dtype).tiny ** 0.5
    qab = a + b
    qap = a + 1.0
    qam = a - 1.0
    c = torch.ones_like(x)
    d = 1.0 - qab * x / qap
    d = torch.where(d.abs() < tiny, torch.full_like(d, tiny), d)
    d = 1.0 / d
    h = d
    for m in range(1, itmax + 1):
        m2 = 2 * m
        aa = m * (b - m) * x / ((qam + m2) * (a + m2))
        d = 1.0 + aa * d
        d = torch.where(d.abs() < tiny, torch.full_like(d, tiny), d)
        c = 1.0 + aa / c
        c = torch.where(c.abs() < tiny, torch.full_like(c, tiny), c)
        d = 1.0 / d
        h = h * d * c
        aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2))
        d = 1.0 + aa * d
        d = torch.where(d.abs() < tiny, torch.full_like(d, tiny), d)
        c = 1.0 + aa / c
        c = torch.where(c.abs() < tiny, torch.full_like(c, tiny), c)
        d = 1.0 / d
        delta = d * c
        h = h * delta
        if bool((delta - 1.0).abs().max() < eps):
            break
    return h


def _positive(raw: Tensor, eps: float) -> Tensor:
    return F.softplus(raw) + eps


def _inverse_softplus(sigma: Tensor, eps: float) -> Tensor:
    # ponytail: inverse of _positive for unconstrained_inputs=False mode.
    # softplus^{-1}(s) = log(expm1(s)) = s + log(-expm1(-s)); the second form
    # never overflows (expm1(s) is inf for s > ~88 in float32).
    s = (sigma - eps).clamp(min=1e-6)
    return s + torch.log(-torch.expm1(-s))


def _as_params(y_pred: Tensor, n_params: int, name: str) -> None:
    if y_pred.shape[-1] < n_params:
        raise ValueError(
            f"{name} expects at least {n_params} columns in the last dim of y_pred, "
            f"got {y_pred.shape[-1]}"
        )


def _align_target(target: Tensor, params: Tensor) -> Tensor:
    if target.dim() == params.dim() - 1:
        return target.unsqueeze(-1)
    return target


def _reduce_elementwise(
    elementwise: Tensor,
    reduction: str,
    mask: Optional[Tensor],
    weights: Optional[Tensor],
) -> Tensor:
    return BaseLoss(reduction=reduction)._reduce(elementwise, mask=mask, weights=weights)


# ---------------------------------------------------------------------------
# skew-normal NLL (Azzalini closed form)
# ---------------------------------------------------------------------------


def skew_normal_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise skew-normal NLL.

    ``y_pred[..., 0]`` location xi, ``[..., 1]`` raw scale (softplus-mapped to
    omega > 0), ``[..., 2]`` skewness alpha. Density:
    ``f(y) = 2/omega * phi(z) * Phi(alpha z)``, ``z = (y - xi)/omega``.
    """
    target = _align_target(target, y_pred)
    xi = y_pred[..., 0:1]
    omega = _positive(y_pred[..., 1:2], eps)
    alpha = y_pred[..., 2:3]
    z = (target - xi) / omega
    log_pdf = (
        math.log(2.0) - _HALF_LOG_2PI - torch.log(omega) - 0.5 * z * z + _log_normal_cdf(alpha * z)
    )
    return -(log_pdf.squeeze(-1))


@register_regression_loss("skew_normal_nll")
class SkewNormalNLLLoss(BaseLoss):
    """Skew-normal NLL (Azzalini 1985). Reduces exactly to Gaussian NLL at alpha=0."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            # y_pred[...,1] already positive sigma; map back through inverse softplus
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
        return self._reduce(
            skew_normal_nll_elementwise(y_pred, target, eps=self.eps), mask, weights
        )


def skew_normal_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional skew-normal NLL."""
    elementwise = skew_normal_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# skew-t NLL (Azzalini-type, lgamma normalized)
# ---------------------------------------------------------------------------


def skew_t_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise skew-t NLL.

    ``y_pred[..., 0]`` location xi, ``[..., 1]`` raw scale, ``[..., 2]``
    skewness alpha, ``[..., 3]`` raw dof nu (softplus-mapped). Density:
    ``f(y) = 2/omega * t_nu(z) * T_{nu+1}(alpha z sqrt((nu+1)/(nu+z^2)))``.
    """
    _as_params(y_pred, 4, "skew_t_nll")
    target = _align_target(target, y_pred)
    xi = y_pred[..., 0:1]
    omega = _positive(y_pred[..., 1:2], eps)
    alpha = y_pred[..., 2:3]
    nu = _positive(y_pred[..., 3:4], eps)
    z = (target - xi) / omega
    log_t_pdf = (
        torch.lgamma((nu + 1.0) / 2.0)
        - torch.lgamma(nu / 2.0)
        - 0.5 * torch.log(nu * math.pi)
        - torch.log(omega)
        - ((nu + 1.0) / 2.0) * torch.log1p(z * z / nu)
    )
    w = alpha * z * torch.sqrt((nu + 1.0) / (nu + z * z))
    log_cdf_term = _student_t_log_cdf_vec(w, nu + 1.0)
    return -(math.log(2.0) + log_t_pdf + log_cdf_term).squeeze(-1)


def _student_t_log_cdf_vec(x: Tensor, df: Tensor) -> Tensor:
    """Log CDF of Student-t with elementwise dof ``df`` (tensor-valued)."""
    xb = df / (df + x * x)
    inc = _reg_inc_beta(df / 2.0, torch.full_like(df, 0.5), xb)
    half_log = math.log(0.5) + torch.log(inc.clamp_min(torch.finfo(inc.dtype).tiny))
    # T(w) = 0.5 * I_x(df/2, 1/2) for w <= 0; 1 - that for w > 0.
    return torch.where(x <= 0.0, half_log, torch.log1p(-torch.exp(half_log.clamp(max=-_TINY_F32))))


def _reg_inc_beta(a: Tensor, b: Tensor, x: Tensor) -> Tensor:
    """Regularized incomplete beta I_x(a, b), elementwise, with the standard
    symmetry branch ``I_x(a, b) = 1 - I_{1-x}(b, a)`` for large x (the
    continued fraction only converges well away from x = 1).

    Computed internally in float64: at fp32 the ``log1p(-x)``/``lgamma``
    backward passes overflow to inf for boundary inputs (x→1, large a/b),
    NaN-ing any net in a few steps (found via skew-t harness smoke).
    The output is a probability — clamped to [0, 1] on return.
    """
    dtype = x.dtype
    device = x.device
    a64 = a.to(torch.float64)
    b64 = b.to(torch.float64)
    x64 = x.to(torch.float64).clamp(torch.finfo(torch.float64).tiny, 1.0 - 1e-15)
    ln_bt = (
        torch.lgamma(a64 + b64)
        - torch.lgamma(a64)
        - torch.lgamma(b64)
        + a64 * torch.log(x64)
        + b64 * torch.log1p(-x64)
    )
    bt = torch.exp(ln_bt)
    sym = x64 > (a64 + 1.0) / (a64 + b64 + 2.0)
    xs = torch.where(sym, 1.0 - x64, x64)
    aa = torch.where(sym, b64, a64)
    bb = torch.where(sym, a64, b64)
    cf = _betacf(aa, bb, xs)
    # Numerical Recipes ``betai``: I_x(a, b) = bt * cf(a, b, x) / a, and under
    # symmetry 1 - bt * cf(b, a, 1 - x) / b. ``aa`` already holds b on the
    # symmetric branch, so both branches divide by ``aa``.
    out = torch.where(sym, 1.0 - bt * cf / aa, bt * cf / aa)
    return out.clamp(0.0, 1.0).to(device=device, dtype=dtype)


@register_regression_loss("skew_t_nll")
class SkewTLoss(BaseLoss):
    """Skew-t NLL (Azzalini & Capitanio 2003), lgamma-normalized."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
            y_pred[..., 3:4] = _inverse_softplus(y_pred[..., 3:4], self.eps)
        return self._reduce(skew_t_nll_elementwise(y_pred, target, eps=self.eps), mask, weights)


def skew_t_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional skew-t NLL."""
    elementwise = skew_t_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# beta regression NLL
# ---------------------------------------------------------------------------


def beta_regression_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise beta-regression NLL.
    ``y_pred[..., 0]`` raw mean logit (sigmoid -> mu in (0,1)), ``[..., 1]``
    raw precision (softplus -> phi > 0). Targets must lie strictly in (0, 1).
    """
    _as_params(y_pred, 2, "beta_regression_nll")
    # Same target alignment as the other family losses: [B] and [B, 1]
    # targets both pair row-wise with [B, 2] params (a [B, 1] target used to
    # broadcast against [B] params into a [B, B] cross-sample loss).
    target = _align_target(target, y_pred)
    mu = torch.sigmoid(y_pred[..., 0:1])
    phi = _positive(y_pred[..., 1:2], eps)
    alpha = mu * phi
    beta = (1.0 - mu) * phi
    if not bool(((target > 0.0) & (target < 1.0)).all()):
        raise ValueError("beta_regression_nll requires targets strictly inside (0, 1)")
    log_norm = torch.lgamma(alpha + beta) - torch.lgamma(alpha) - torch.lgamma(beta)
    log_pdf = log_norm + (alpha - 1.0) * torch.log(target) + (beta - 1.0) * torch.log1p(-target)
    return -(log_pdf.squeeze(-1))


@register_regression_loss("beta_regression_nll")
class BetaRegressionNLLLoss(BaseLoss):
    """Beta-regression NLL (Ferrari & Cribari-Neto 2004) for targets in (0, 1)."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
        return self._reduce(
            beta_regression_nll_elementwise(y_pred, target, eps=self.eps), mask, weights
        )


def beta_regression_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional beta-regression NLL."""
    elementwise = beta_regression_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# Johnson SU NLL
# ---------------------------------------------------------------------------


def johnson_su_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise Johnson-SU NLL.

    ``y_pred[..., 0]`` location xi, ``[..., 1]`` raw scale lambda
    (softplus-mapped), ``[..., 2]`` shape gamma, ``[..., 3]`` raw shape delta
    (softplus-mapped). Standardized variate: ``Z = gamma + delta*asinh(u)``,
    ``u = (y - xi)/lambda`` (Shenton-quadrant moment interpretation applies to
    (gamma, delta)).
    """
    _as_params(y_pred, 4, "johnson_su_nll")
    target = _align_target(target, y_pred)
    xi = y_pred[..., 0:1]
    lam = _positive(y_pred[..., 1:2], eps)
    gamma = y_pred[..., 2:3]
    delta = _positive(y_pred[..., 3:4], eps)
    u = (target - xi) / lam
    z = gamma + delta * torch.asinh(u)
    nll = _HALF_LOG_2PI - torch.log(delta) + torch.log(lam) + 0.5 * torch.log1p(u * u) + 0.5 * z * z
    return nll.squeeze(-1)


@register_regression_loss("johnson_su_nll")
class JohnsonSUNLLLoss(BaseLoss):
    """Johnson-SU NLL (Shenton-quadrant (gamma, delta) shapes)."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
            y_pred[..., 3:4] = _inverse_softplus(y_pred[..., 3:4], self.eps)
        return self._reduce(johnson_su_nll_elementwise(y_pred, target, eps=self.eps), mask, weights)


def johnson_su_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional Johnson-SU NLL."""
    elementwise = johnson_su_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# sinh-arcsinh NLL (Jones & Pewsey)
# ---------------------------------------------------------------------------


def sinh_arcsinh_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise sinh-arcsinh NLL.

    ``y_pred[..., 0]`` location mu, ``[..., 1]`` raw scale sigma,
    ``[..., 2]`` skewness epsilon, ``[..., 3]`` raw tail-weight delta
    (softplus-mapped). With ``z = (y - mu)/sigma`` and
    ``s = sinh((asinh(z) - epsilon)/delta)`` (the inverse of the Jones &
    Pewsey transformation ``x = mu + sigma*sinh(delta*asinh(Z) + epsilon)``
    for standard-normal Z), the NLL is
    ``0.5*log(2 pi) + log(sigma*delta) + 0.5*log1p(z^2)
    - 0.5*log1p(s^2) + s^2/2``.
    At epsilon=0, delta=1 this reduces exactly to the Gaussian NLL.
    """
    _as_params(y_pred, 4, "sinh_arcsinh_nll")
    target = _align_target(target, y_pred)
    mu = y_pred[..., 0:1]
    sigma = _positive(y_pred[..., 1:2], eps)
    skew_eps = y_pred[..., 2:3]
    delta = _positive(y_pred[..., 3:4], eps)
    z = (target - mu) / sigma
    w = (torch.asinh(z) - skew_eps) / delta
    s = torch.sinh(w)
    nll = (
        _HALF_LOG_2PI
        + torch.log(sigma)
        + torch.log(delta)
        + 0.5 * torch.log1p(z * z)
        - 0.5 * torch.log1p(s * s)
        + 0.5 * s * s
    )
    return nll.squeeze(-1)


@register_regression_loss("sinh_arcsinh_nll")
class SinhArcsinhNLLLoss(BaseLoss):
    """Sinh-arcsinh NLL (Jones & Pewsey 2009); Gaussian at epsilon=0, delta=1."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
            y_pred[..., 3:4] = _inverse_softplus(y_pred[..., 3:4], self.eps)
        return self._reduce(
            sinh_arcsinh_nll_elementwise(y_pred, target, eps=self.eps), mask, weights
        )


def sinh_arcsinh_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional sinh-arcsinh NLL."""
    elementwise = sinh_arcsinh_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# GEV NLL (xi -> 0 Gumbel limit analytic)
# ---------------------------------------------------------------------------

_GUMBEL_XI_THRESHOLD = 1e-6


def gev_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise generalized-extreme-value NLL (Coles parameterization).

    ``y_pred[..., 0]`` location mu, ``[..., 1]`` raw scale sigma
    (softplus-mapped), ``[..., 2]`` shape xi. For |xi| below
    ``_GUMBEL_XI_THRESHOLD`` the analytic Gumbel limit is used. Observations
    outside the support ``1 + xi*z > 0`` receive infinite NLL.
    """
    _as_params(y_pred, 3, "gev_nll")
    target = _align_target(target, y_pred)
    mu = y_pred[..., 0:1]
    sigma = _positive(y_pred[..., 1:2], eps)
    xi = y_pred[..., 2:3]
    z = (target - mu) / sigma
    use_gumbel = xi.abs() < _GUMBEL_XI_THRESHOLD
    # ponytail: torch.where does not short-circuit, and its backward multiplies
    # the unused branch's local derivative by 0 (0 * inf = NaN). Every branch
    # therefore only sees inputs it is valid for: z is zeroed outside the
    # Gumbel branch (exp(-z) overflows for far-left targets on the GEV branch)
    # and xi*z outside the supported GEV branch.
    z_gumbel = torch.where(use_gumbel, z, torch.zeros_like(z))
    gumbel = torch.log(sigma) + z_gumbel + torch.exp(-z_gumbel)
    xz = xi * z
    supported = xz > -1.0  # t = 1 + xi*z > 0
    use_gev = (~use_gumbel) & supported
    xi_safe = torch.where(use_gev, xi, torch.full_like(xi, _GUMBEL_XI_THRESHOLD))
    xz_safe = torch.where(use_gev, xz, torch.zeros_like(xz))
    # log t = log1p(xi*z): forming t = 1 + xi*z first loses the low bits of
    # xi*z, an error that 1/xi amplifies to O(0.1) nats in float32 just above
    # the Gumbel threshold.
    log_t = torch.log1p(xz_safe)
    gev_raw = torch.log(sigma) + (1.0 + 1.0 / xi_safe) * log_t + torch.exp(-log_t / xi_safe)
    gev = torch.where(supported, gev_raw, torch.full_like(gev_raw, float("inf")))
    return torch.where(use_gumbel, gumbel, gev).squeeze(-1)


@register_regression_loss("gev_nll")
class GEVNLLLoss(BaseLoss):
    """GEV NLL with an analytic Gumbel limit as xi -> 0."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
        return self._reduce(gev_nll_elementwise(y_pred, target, eps=self.eps), mask, weights)


def gev_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional GEV NLL."""
    elementwise = gev_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# asymmetric Laplace NLL (kappa <-> tau pinball correspondence)
# ---------------------------------------------------------------------------


def asymmetric_laplace_nll_elementwise(y_pred: Tensor, target: Tensor, eps: float = 1e-6) -> Tensor:
    """Elementwise asymmetric-Laplace NLL.

    ``y_pred[..., 0]`` location mu, ``[..., 1]`` raw scale sigma
    (softplus-mapped), ``[..., 2]`` raw shape kappa (softplus-mapped, > 0).

    Density: ``f(y) = sqrt(2)*kappa/(sigma*(1+kappa^2)) *
    exp(-(sqrt(2)/(sigma*kappa))*max(y-mu, 0) - (sqrt(2)*kappa/sigma)*max(mu-y, 0))``.
    The negative log-likelihood equals its normalization constant plus
    ``(sqrt(2)*(1+kappa^2)/(sigma*kappa)) * rho_tau(y - mu)`` where
    ``rho_tau`` is the pinball/check loss at the quantile level
    ``tau = 1/(1 + kappa^2)`` — i.e. the kappa-tau correspondence.
    """
    _as_params(y_pred, 3, "asymmetric_laplace_nll")
    target = _align_target(target, y_pred)
    mu = y_pred[..., 0:1]
    sigma = _positive(y_pred[..., 1:2], eps)
    kappa = _positive(y_pred[..., 2:3], eps)
    u = target - mu
    above = u >= 0.0
    rate = torch.where(above, 1.0 / kappa, kappa) * (_SQRT2 / sigma)
    log_norm = math.log(_SQRT2) + torch.log(kappa) - torch.log(sigma) - torch.log1p(kappa * kappa)
    nll = -log_norm + rate * torch.abs(u)
    return nll.squeeze(-1)


@register_regression_loss("asymmetric_laplace_nll")
class AsymmetricLaplaceNLLLoss(BaseLoss):
    """Asymmetric-Laplace NLL; reduces to the scaled pinball NLL at
    ``tau = 1/(1 + kappa**2)``."""

    def __init__(
        self, eps: float = 1e-6, reduction: str = "mean", unconstrained_inputs: bool = True
    ) -> None:
        super().__init__(reduction=reduction)
        self.eps = eps
        self.unconstrained_inputs = unconstrained_inputs

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        if not self.unconstrained_inputs:
            y_pred = y_pred.clone()
            y_pred[..., 1:2] = _inverse_softplus(y_pred[..., 1:2], self.eps)
            y_pred[..., 2:3] = _inverse_softplus(y_pred[..., 2:3], self.eps)
        return self._reduce(
            asymmetric_laplace_nll_elementwise(y_pred, target, eps=self.eps), mask, weights
        )


def asymmetric_laplace_nll(
    y_pred: Tensor,
    target: Tensor,
    *,
    eps: float = 1e-6,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional asymmetric-Laplace NLL."""
    elementwise = asymmetric_laplace_nll_elementwise(y_pred, target, eps=eps)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


# ---------------------------------------------------------------------------
# SQR loss (sorted quantile levels, mean pinball)
# ---------------------------------------------------------------------------


def sqr_loss_elementwise(y_pred: Tensor, target: Tensor, n_levels: Optional[int] = None) -> Tensor:
    """Elementwise SQR loss (Duan et al. 2020).

    ``y_pred[..., j]`` are the L=``n_levels`` quantile-level predictions; they
    are made monotone with a running maximum (:func:`torch.cummax`) so the
    predicted quantile curve is sorted by construction. The loss is the mean
    pinball across levels ``tau_j = j/(L+1)``.
    """
    if y_pred.dim() < 2:
        raise ValueError(
            f"sqr_loss expects [batch, levels] predictions, got shape {tuple(y_pred.shape)}"
        )
    levels = y_pred.shape[1]
    if n_levels is not None and levels != n_levels:
        raise ValueError(f"sqr_loss expected {n_levels} levels, got {levels}")
    sorted_q = torch.cummax(y_pred, dim=1).values
    tau = torch.arange(1, levels + 1, device=y_pred.device, dtype=y_pred.dtype) / (levels + 1.0)
    if target.dim() == y_pred.dim() - 1:
        target = target.unsqueeze(-1)
    elif target.dim() != y_pred.dim() or target.shape[-1] != 1:
        # A [B, 1] target broadcasts against [B, L]; anything else (e.g. the
        # old ``target.unsqueeze(-1)`` of a [B, 1] target) would silently pair
        # every sample with every other sample.
        raise ValueError(
            f"sqr_loss expects targets of shape {tuple(y_pred.shape[:-1])} or "
            f"{tuple(y_pred.shape[:-1]) + (1,)}, got {tuple(target.shape)}"
        )
    diff = target - sorted_q
    pinball = torch.maximum(tau * diff, (tau - 1.0) * diff)
    return pinball.mean(dim=-1)


@register_regression_loss("sqr_loss")
class SQRLoss(BaseLoss):
    """Distributional quantile regression via sorted levels + mean pinball
    (Duan et al., 2020). The head outputs L quantile levels; monotonicity is
    enforced with a cumulative max."""

    def __init__(self, n_levels: int = 32, reduction: str = "mean") -> None:
        super().__init__(reduction=reduction)
        self.n_levels = n_levels

    def forward(
        self,
        y_pred: Tensor,
        target: Tensor,
        mask: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        **kw: object,
    ) -> Tensor:
        return self._reduce(
            sqr_loss_elementwise(y_pred, target, n_levels=self.n_levels), mask, weights
        )


def sqr_loss(
    y_pred: Tensor,
    target: Tensor,
    *,
    n_levels: int = 32,
    reduction: str = "mean",
    mask: Optional[Tensor] = None,
    weights: Optional[Tensor] = None,
) -> Tensor:
    """Functional SQR loss over ``n_levels`` sorted quantile levels."""
    elementwise = sqr_loss_elementwise(y_pred, target, n_levels=n_levels)
    return _reduce_elementwise(elementwise, reduction, mask, weights)


__all__ = [
    "AsymmetricLaplaceNLLLoss",
    "BetaRegressionNLLLoss",
    "GEVNLLLoss",
    "JohnsonSUNLLLoss",
    "SQRLoss",
    "SinhArcsinhNLLLoss",
    "SkewNormalNLLLoss",
    "SkewTLoss",
    "asymmetric_laplace_nll",
    "beta_regression_nll",
    "gev_nll",
    "johnson_su_nll",
    "sqr_loss",
    "sinh_arcsinh_nll",
    "skew_normal_nll",
    "skew_t_nll",
]
